{% set name = "geo-parameters" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geo_parameters-{{ version }}.tar.gz
  sha256: dc9e664b3d6e3bf81ea682c077ff3dde9df5471eb0e993a376dbe0ac9b2e95ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.9
    - pip
    - setuptools
  run:
    - python 3.9
    - numpy
    - pint

test:
  imports:
    - geo_parameters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bjorkqvi/geo-parameters
  summary: Metadata of geophysical (especially wave) parameters
  description: Metadata of geophysical (especially wave) parameters
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bjorkqvi/geo-parameters


extra:
  recipe-maintainers:
    - bjorkqvi
