{% set name = "geo-parameters" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geo_parameters-{{ version }}.tar.gz
  sha256: b408cc0d376471b1ee1e123737a5aacf77b8dd1128b8fed21c9d1821e24444ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - pip >=24.3.1
    - setuptools
  run:
    - python >=3.9,<3.12
    - numpy
    - pint

test:
  imports:
    - geo_parameters
  commands:
    - pip check
  requires:
    - pip >=24.3.1

about:
  home: https://github.com/bjorkqvi/geo-parameters
  summary: Metadata of geophysical (especially wave) parameters
  description: Metadata of geophysical (especially wave) parameters
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bjorkqvi/geo-parameters


extra:
  recipe-maintainers:
    - bjorkqvi
