{% set name = "geo-parameters" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geo_parameters-{{ version }}.tar.gz
  sha256: 50ed0cba48937aa8c56d52abb32ba023484c3169b7c0b978c8e26a5f490aef76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - geo_parameters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bjorkqvi/geo-parameters
  summary: Metadata of geophysical (especially wave) parameters
  description: Metadata of geophysical (especially wave) parameters
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bjorkqvi/geo-parameters


extra:
  recipe-maintainers:
    - bjorkqvi
