{% set name = "geo-parameters" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geo_parameters-{{ version }}.tar.gz
  sha256: 8c1215c8f2bdd8327fa8c6e58f6bb4faeaefc9e541bb7a6d3cd1abc24448e0be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pint

test:
  imports:
    - geo_parameters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bjorkqvi/geo-parameters
  summary: Metadata of geophysical (especially wave) parameters
  description: Metadata of geophysical (especially wave) parameters
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bjorkqvi/geo-parameters


extra:
  recipe-maintainers:
    - bjorkqvi
