{% set name = "geo-parameters" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geo_parameters-{{ version }}.tar.gz
  sha256: 05bacaa71c2054fe6ac3da42bf66e4ef1b2cc2b6fbba40e74b4a53e3bff149cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9,<=3.13
    - pip
    - setuptools
  run:
    - python >=3.9,<=3.13
    - numpy

test:
  imports:
    - geo_parameters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bjorkqvi/geo-parameters
  summary: Metadata of geophysical (especially wave) parameters
  description: Metadata of geophysical (especially wave) parameters
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/bjorkqvi/geo-parameters


extra:
  recipe-maintainers:
    - bjorkqvi
